### ISSUE TITLE
upgrade e mantenimento

### ISSUE THREAD

**Issue by francescor** [italia/dati-ckan-docker#10]
vorremmo mettere in produzione il docker, ma abbiamo timori sul mantenimento di questo setup docker rispetto ad una installazione ordinaria: quanto praticabile/conveniente pensate sia mantenere aggiornato il software (ckan) entro il docker?

**Comment by fabiofumarola** [comment]
Ciao in particolare quali sono i tuoi dubbi?
Se vedi il compose utilizza postgres, mongodb, solr e redis. Mi sembra che mongodb non sia utilizzato.
L'unica cosa di cui ti devi sincerare prima di mettere in produzione questo compose e' la persistenza dei dati. Questo puo' essere fatto in due modi: 1. bind di cartelle dell tuo filel system (cosa che ti consiglio solo se usi una distro linux) oppure tramite [volumi](https://docs.docker.com/engine/admin/volumes/volumes/#differences-between--v-and---mount-behavior).
Basta creare un volume per salvare i dati dei db che ti interessano e fare un backup di questi volumi / riutilizzarli in caso di restart della applicazione.

Se mi dai maggiori dettagli possiamo lavorare a un fork del progetto per la tua esigenza e poi magari fare un pull request se lo riteniamo utile alla community.

```
ckan:
  container_name: ckan
  image: daf-ckan:1.0.0
  links:
      - db
      - solr
      - redis
  ports:
      - "5000:5000"
  environment:
      - CKAN_SITE_URL=http://localhost:5000
      - DB_PORT_5432_TCP_ADDR=db
      - SOLR_PORT_8983_TCP_ADDR=solr
      - REDIS_PORT_6379_TCP_ADDR=redis

db:
  container_name: db
  image: ckan/postgresql:latest
  
solr:
  container_name: solr
  image: daf-ckan-solr:1.0.0
    
redis:
  container_name: redis
  image: redis:latest

mongodb:
  container_name: mongo
  image: bitnami/mongodb:latest
  ports:
      - "27017:27017"
  environment:
      - MONGODB_ROOT_PASSWORD=mongo
      - MONGODB_USERNAME=ckan
      - MONGODB_PASSWORD=ckan
      - MONGODB_DATABASE=ckan
```
